services:
  - type: web
    name: residea-core-api
    env: python
    plan: free
    rootDir: core-backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python create_admin.py
    startCommand: gunicorn residea_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: USE_SQLITE
        value: "False"
      - key: DATABASE_URL
        sync: false # This tells Render to ask YOU for the string
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: "*"

  - type: web
    name: residea-ai-backend
    env: python
    plan: free
    rootDir: ai-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: GRADIO_HF_TOKEN
        sync: false # Render will ask you for your HuggingFace token
